/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DsfrAccordion: typeof import('@gouvminint/vue-dsfr')['DsfrAccordion']
    DsfrAccordionsGroup: typeof import('@gouvminint/vue-dsfr')['DsfrAccordionsGroup']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrBadge: typeof import('@gouvminint/vue-dsfr')['DsfrBadge']
    DsfrBreadcrumb: typeof import('@gouvminint/vue-dsfr')['DsfrBreadcrumb']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrFooter: typeof import('@gouvminint/vue-dsfr')['DsfrFooter']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
    DsfrRange: typeof import('@gouvminint/vue-dsfr')['DsfrRange']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
