/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/contenus/': RouteRecordInfo<'/admin/contenus/', '/admin/contenus', Record<never, never>, Record<never, never>>,
    '/admin/contenus/[id]': RouteRecordInfo<'/admin/contenus/[id]', '/admin/contenus/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/contenus/creer': RouteRecordInfo<'/admin/contenus/creer', '/admin/contenus/creer', Record<never, never>, Record<never, never>>,
    '/admin/emotions/': RouteRecordInfo<'/admin/emotions/', '/admin/emotions', Record<never, never>, Record<never, never>>,
    '/admin/utilisateurs/': RouteRecordInfo<'/admin/utilisateurs/', '/admin/utilisateurs', Record<never, never>, Record<never, never>>,
    '/admin/utilisateurs/[id]': RouteRecordInfo<'/admin/utilisateurs/[id]', '/admin/utilisateurs/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/auth/connexion': RouteRecordInfo<'/auth/connexion', '/auth/connexion', Record<never, never>, Record<never, never>>,
    '/auth/inscription': RouteRecordInfo<'/auth/inscription', '/auth/inscription', Record<never, never>, Record<never, never>>,
    '/erreur': RouteRecordInfo<'/erreur', '/erreur', Record<never, never>, Record<never, never>>,
    '/informations/': RouteRecordInfo<'/informations/', '/informations', Record<never, never>, Record<never, never>>,
    '/informations/[id]': RouteRecordInfo<'/informations/[id]', '/informations/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/profil': RouteRecordInfo<'/profil', '/profil', Record<never, never>, Record<never, never>>,
    '/tracker/': RouteRecordInfo<'/tracker/', '/tracker', Record<never, never>, Record<never, never>>,
    '/tracker/[id]': RouteRecordInfo<'/tracker/[id]', '/tracker/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tracker/ajouter': RouteRecordInfo<'/tracker/ajouter', '/tracker/ajouter', Record<never, never>, Record<never, never>>,
    '/tracker/historique': RouteRecordInfo<'/tracker/historique', '/tracker/historique', Record<never, never>, Record<never, never>>,
    '/tracker/rapports': RouteRecordInfo<'/tracker/rapports', '/tracker/rapports', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...404].vue': {
      routes: '/[...404]'
      views: never
    }
    'src/pages/admin/index.vue': {
      routes: '/admin/'
      views: never
    }
    'src/pages/admin/contenus/index.vue': {
      routes: '/admin/contenus/'
      views: never
    }
    'src/pages/admin/contenus/[id].vue': {
      routes: '/admin/contenus/[id]'
      views: never
    }
    'src/pages/admin/contenus/creer.vue': {
      routes: '/admin/contenus/creer'
      views: never
    }
    'src/pages/admin/emotions/index.vue': {
      routes: '/admin/emotions/'
      views: never
    }
    'src/pages/admin/utilisateurs/index.vue': {
      routes: '/admin/utilisateurs/'
      views: never
    }
    'src/pages/admin/utilisateurs/[id].vue': {
      routes: '/admin/utilisateurs/[id]'
      views: never
    }
    'src/pages/auth/connexion.vue': {
      routes: '/auth/connexion'
      views: never
    }
    'src/pages/auth/inscription.vue': {
      routes: '/auth/inscription'
      views: never
    }
    'src/pages/erreur.vue': {
      routes: '/erreur'
      views: never
    }
    'src/pages/informations/index.vue': {
      routes: '/informations/'
      views: never
    }
    'src/pages/informations/[id].vue': {
      routes: '/informations/[id]'
      views: never
    }
    'src/pages/profil.vue': {
      routes: '/profil'
      views: never
    }
    'src/pages/tracker/index.vue': {
      routes: '/tracker/'
      views: never
    }
    'src/pages/tracker/[id].vue': {
      routes: '/tracker/[id]'
      views: never
    }
    'src/pages/tracker/ajouter.vue': {
      routes: '/tracker/ajouter'
      views: never
    }
    'src/pages/tracker/historique.vue': {
      routes: '/tracker/historique'
      views: never
    }
    'src/pages/tracker/rapports.vue': {
      routes: '/tracker/rapports'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
